services:
  - type: web
    name: crusestick
    runtime: php
    plan: free
    buildCommand: ./build.sh
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: CruseStick
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        value: postgresql://cursestock_user:aKP60RR6ZwzX6ddYtUOCbTGJj3lBYTmm@dpg-d0tcncadbo4c739hp6t0-a.frankfurt-postgres.render.com/cursestock
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync